### ISSUE TITLE
Do not overwrite my setup

### ISSUE THREAD

**Issue by monkpit** [RyanKung/stack#3]
The `stack init` command has downloaded and installed some dev version of pip (that I do not want).

Now if I run any `pip[2|3] --version` I get the dev version. I didn't want the dev version, why did you change it without asking me?

Now if I run `mkvirtualenv test` I am given python3.5 - I don't want python3.5 by default, why did you change it without asking me? `VIRTUALENVWRAPPER_PYTHON` is `/usr/local/bin/python` still. `/usr/local/bin/python --version` is `2.7.11`. Why are you giving me python3 now when I create a virtualenv?

**Comment by RyanKung** [comment]
@monkpit Thanks for your response
- about `dev version pip`
  
  `Stack` will install the `dev version` of `pip` which I forked from the origin pip. Because there is some hidden bug on `pip._vendor.distlib`. When calling a command with `os.system`, `subprocess.call` or `fabric.api.local`, it will add wrong `shabang` on the `executable` files, such as `nosetests` or `scafford`.

**And `YES`, I should ask you before change it.**

ref : 

https://github.com/pypa/pip/issues/3649
https://github.com/pypa/pip/pull/3650
- about virtualenv

`Stack` won't change your virtualenv setting, It just installed latest virtualenv (15.0.1 for now), and the default setting of that venv is python3.

**Comment by RyanKung** [comment]
Hi @monkpit 

`pip install pip --upgrade`

You may need run this to fix your pip, because after installed `python-stack`, the default pip was replaced to the 'forked version of pip',  you need to reinstall pip for fix that, I'm so sorry for this, it's a mistake.

And he new version of `stack` will give up the `forked pip`, just using the default system pip.

New stack will scan all scripts under osconfig.get_path('scripts'), and register as tasks. 

It's still unstable (I should note that), and needing more issue/pullrequest.

Thanks.
